{
 "title": "Spark Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "applicationId", "query": "*" },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "active tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "spark-metrics.$applicationId.*.executor.threadpool.activeTasks"
    }
   ]
  },
  {
   "title": "cores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "spark-metrics.$applicationId.*.executor.threadpool.currentPool_size"
    }
   ]
  },
  {
   "title": "shuffle read",
   "type": "timeseries",
   "description": "Total shuffle bytes and records read (includes both data read locally and data read from remote executors)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "spark-metrics.$applicationId.*.executor.shuffleTotalBytesRead.*"
    }
   ]
  },
  {
   "title": "completed tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "spark-metrics.$applicationId.*.executor.threadpool.completeTasks"
    }
   ]
  },
  {
   "title": "hdfs read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "refCount": 1,
     "target": "spark-metrics.$applicationId.*.executor.filesystem.hdfs.read_bytes"
    }
   ]
  },
  {
   "title": "shuffle write",
   "type": "timeseries",
   "description": "bytes and  records written to disk in order to be read by s shuffle in a future stage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "spark-metrics.$applicationId.*.executor.shuffleBytesWritten.*"
    }
   ]
  },
  { "title": "Streaming Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "applicationId" },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "averageAbove(spark-metrics.$applicationId.driver.spark.streaming.3da91723-d4a3-4bb3-84ed-59d9b71290cb.latency, 0)"
    }
   ]
  },
  {
   "title": "Input Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "target": "averageAbove(spark-metrics.$applicationId.driver.spark.streaming.3da91723-d4a3-4bb3-84ed-59d9b71290cb.inputRate-total, 0)"
    }
   ]
  },
  {
   "title": "Process Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "target": "averageAbove(spark-metrics.$applicationId.driver.spark.streaming.3da91723-d4a3-4bb3-84ed-59d9b71290cb.processingRate-total, 0)"
    }
   ]
  }
 ]
}